### ISSUE TITLE
Initial source code alternative location than Scrimba.

### ISSUE THREAD

**Issue by sourav-paul** [kevin-powell/reponsive-web-design-bootcamp#1]
Is there an alternative to Scrimba where the initial codes are available? Scrimba is not allowing to see the contents.

**Comment by kevin-powell** [comment]
All the initial code is here, but it's all from the Scrimba course itself. When you say you can't see the content, what do you mean exactly?

**Comment by sourav-paul** [comment]
It seems to be under a paid subscription. I was following from free code camp. Code here seems not the same. In the tutorial, it's ~70 lines of CSS, here it's over 300 lines. From youtube comments, a lot of people were unable to access the code as well it seems.

**Comment by kevin-powell** [comment]
Oh, correct. The Code here is for the course. Scrimba decided to share a section of the course for free on FCC. These files here are meant to complement the paid course on Scrimba, and not the FCC part that was pulled out.

**Comment by sourav-paul** [comment]
Is the initial source available anywhere else?  Or is it possible for you to share in the open? If not, I'll close the issue.

**Comment by sourav-paul** [comment]
Closing it anyway. Seems an irrelevant issue.
